spring.application.name=springbootapp1
server.max-http-request-header-size=16KB
spring.datasource.url=jdbc:mysql://localhost:3306/spring_boot_db?serverTimeZone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Loga@2007
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=create-drop


